/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import common.Global;
import dao.UserDao;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import views.movie.MovieList;
import views.room.RoomList;
import views.showing.ShowingList;
import views.user.Home;
import views.user.UserList;

/**
 *
 * @author caster
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
//        Global.user = (UserDao) new UserDao().where("id", "=", "5").first();
        initComponents();
        generateMenu();
    }

    public void generateMenu () {
        UserDao user = Global.user;
        if (user != null) {
            Container c = getContentPane();
            setBounds(300, 200, 200, 300);
            JButton profileButton = new JButton("个人信息");
            c.add(profileButton);
            
            JButton movieButton = new JButton("电影管理");
            c.add(movieButton);

            JButton roomButton = new JButton("放映厅管理");
            c.add(roomButton);

            JButton showingButton = new JButton("放映场次管理");
            c.add(showingButton);

            profileButton.addActionListener(new ProfileButtonClickLinstener());
            movieButton.addActionListener(new MovieButtonClickLinstener());
            roomButton.addActionListener(new RoomButtonClickLinstener());
            showingButton.addActionListener(new ShowingButtonClickLinstener());
            
            if (user.isRole("Administrator")) {
                JButton userButton = new JButton("用户管理");
                c.add(userButton);
                userButton.addActionListener(new UserButtonClickLinstener());
            }
        }
    }
    
    private class ProfileButtonClickLinstener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent event) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Home().setVisible(true);
                }
            });
        }
    }

    private class MovieButtonClickLinstener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent event) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MovieList().setVisible(true);
                }
            });
        }
    }

    private class ShowingButtonClickLinstener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent event) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ShowingList().setVisible(true);
                }
            });
        }
    }

    private class RoomButtonClickLinstener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent event) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new RoomList().setVisible(true);
                }
            });
        }
    }

    private class UserButtonClickLinstener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent event) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new UserList().setVisible(true);
                }
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 300, 400));
        getContentPane().setLayout(new java.awt.GridLayout(0, 1, 8, 8));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
